const GET_ALL_DOGS = 'GET_ALL_DOGS';
const DOG_DETAIL = 'DOG_DETAIL';
const GET_BY_NAME = 'GET_BY_NAME';
const POST_DOG = 'POST_DOG';
const GET_TEMPERAMENT = 'GET_TEMPERAMENT';
const CLEAN_DETAIL = 'CLEAN_DETAIL';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT';
const TEMPERAMENT_FILTER = 'TEMPERAMENT_FILTER';


export {
    GET_ALL_DOGS,
    DOG_DETAIL,
    GET_BY_NAME,
    POST_DOG, 
    GET_TEMPERAMENT,
    CLEAN_DETAIL,
    ORDER_BY_NAME, 
    ORDER_BY_WEIGHT,
    TEMPERAMENT_FILTER
}